# Generated by Django 6.0.7 on 2026-07-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='hotelsetting',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_logos/'),
        ),
    ]
